spring.application.name=demo
# server.port=8090
# filepath: src/main/resources/application.properties
# MS SQL Server DataSource
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

# JPA Properties (可選, 如果使用 Spring Data JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect # 早期版本可能需要 SQLServer2012Dialect 或更新版本